<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rig2Cast.Adapters.Rigctld\Rig2Cast.Adapters.Rigctld.csproj" />
    <ProjectReference Include="..\..\src\Rig2Cast.Drivers.Yaesu\Rig2Cast.Drivers.Yaesu.csproj" />
    <ProjectReference Include="..\..\src\Rig2Cast.Core\Rig2Cast.Core.csproj" />
    <ProjectReference Include="..\..\src\Rig2Cast.Runtime\Rig2Cast.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Rig2Cast.Simulator\Rig2Cast.Simulator.csproj" />
    <ProjectReference Include="..\..\src\Rig2Cast.Transports\Rig2Cast.Transports.csproj" />
  </ItemGroup>
</Project>
